"""Package the pinned, qualified GBasis Python implementation with setuptools."""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
from urllib.request import urlopen
import zipfile

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'outputs'
COMMIT = '071969c900d6d7a9fbbdfe193c65ba3be177fbdf'
SOURCE_HASH = '42c80656a3a744ad528d69c6cb5a7c805c1278ce3d560f822f8a3ca3848e43d4'
VERSION = '0.1.0+qcblender.071969c.pure1'


def main():
    base = OUT / 'build-sources'
    base.mkdir(parents=True, exist_ok=True)
    url = f'https://codeload.github.com/theochem/gbasis/zip/{COMMIT}'
    archive = base / f'gbasis-{COMMIT}.zip'
    if not archive.exists():
        with urlopen(url, timeout=120) as response:
            archive.write_bytes(response.read())
    if hashlib.sha256(archive.read_bytes()).hexdigest() != SOURCE_HASH:
        raise ValueError('Pinned GBasis source checksum mismatch')
    source_record = {'name': 'gbasis', 'commit': COMMIT, 'url': url, 'sha256': SOURCE_HASH,
                     'packaging': 'Python modules only; optional libcint wrapper/native sources excluded'}
    (ROOT / 'science-sources.lock.json').write_text(json.dumps([source_record], indent=2) + '\n', encoding='utf-8')
    with tempfile.TemporaryDirectory(prefix='gbasis-python-', dir=OUT) as temporary:
        stage = Path(temporary)
        with zipfile.ZipFile(archive) as package:
            prefix = f'gbasis-{COMMIT}/'
            for info in package.infolist():
                relative = info.filename.removeprefix(prefix)
                wanted = (relative.startswith('gbasis/') and relative.endswith('.py')
                          and relative != 'gbasis/integrals/libcint.py') or relative in ('LICENSE', 'README.md')
                if wanted:
                    target = stage / relative
                    if not target.resolve().is_relative_to(stage.resolve()):
                        raise ValueError('Unsafe archive member')
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_bytes(package.read(info))
        note = ('QCBlender distribution of GBasis commit ' + COMMIT + '\n'
                'Numerical Python modules are unmodified. Optional libcint wrapper and native code are excluded.\n'
                'Build metadata is generated by tools/build_science_backend.py; upstream license text is retained.\n')
        (stage / 'gbasis/QCBLENDER_BUILD.md').write_text(note, encoding='utf-8')
        (stage / 'pyproject.toml').write_text(f'''[build-system]
requires = ["setuptools==84.0.0"]
build-backend = "setuptools.build_meta"
[project]
name = "qc-gbasis"
version = "{VERSION}"
description = "QCBlender build of the GBasis Python implementation"
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [{{name = "QC-Devs Community"}}]
dependencies = ["numpy>=2.0", "scipy>=1.13.0", "importlib_resources", "sympy"]
[tool.setuptools.packages.find]
include = ["gbasis*"]
[tool.setuptools.package-data]
gbasis = ["QCBLENDER_BUILD.md"]
''', encoding='utf-8')
        env = os.environ.copy()
        env.update(PYTHONPATH=str(OUT / 'build-site'), PYTHONNOUSERSITE='1', PYTHONUTF8='1',
                   TEMP=str(OUT / 'process-temp'), TMP=str(OUT / 'process-temp'))
        (OUT / 'process-temp').mkdir(exist_ok=True)
        subprocess.run([sys.executable, '-m', 'build', '--wheel', '--no-isolation',
                        '--outdir', str(OUT / 'wheels'), str(stage)], env=env, check=True)
    wheel = OUT / 'wheels' / f'qc_gbasis-{VERSION}-py3-none-any.whl'
    with zipfile.ZipFile(wheel) as package:
        assert not any(name.endswith(('.pyd', '.dll', '.so')) or 'libcint' in name for name in package.namelist())
    record = {'name': 'qc-gbasis', 'version': VERSION, 'filename': wheel.name,
              'sha256': hashlib.sha256(wheel.read_bytes()).hexdigest(), 'source_lock': 'science-sources.lock.json',
              'backend': 'Python/NumPy Gaussian basis and Coulomb integrals'}
    (OUT / 'backend-wheel.json').write_text(json.dumps(record, indent=2) + '\n', encoding='utf-8')
    print('Qualified implementation packaged: ' + wheel.name)


if __name__ == '__main__':
    main()
